### ISSUE TITLE
Images not rendering from S3

### ISSUE THREAD

**Issue by lalkrishnak** [stephenyeargin/hubot-grafana#61]
Hi,

I'm getting below error while executing "graf db dashboard-name" command in Slack.

[Thu Oct 12 2017 03:11:52 GMT+0000 (UTC)] ERROR TypeError: msg.replace is not a function
  at SlackBot.send (/root/hubot/node_modules/hubot-slack/src/slack.coffee:229:47, <js>:278:19)
  at runAdapterSend (/root/hubot/node_modules/hubot/src/response.coffee:82:34, <js>:87:50)
  at allDone (/root/hubot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /root/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/root/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/root/hubot/node_modules/async/lib/async.js:268:15)
  at /root/hubot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)

I have configured S3 with Grafana and images are pulled to S3. graf list command is working as expected. Any idea?

**Comment by stephenyeargin** [comment]
Can you confirm that you are running the latest `hubot-slack` package? Not entirely sure what may be calling a `replace` function in this package.

**Comment by lalkrishnak** [comment]
Its working as expected after the upgrade. Thank you.
